### ISSUE TITLE
Does not escape - and / in regexes

### ISSUE THREAD

**Issue by netei** [eventualbuddha/decaffeinate#104]
The code compiles correctly on decaffeinate@1.41.2 
The code doesn't compiles correctly on decaffeinate@1.41.3

```
str.replace(/[\-\/]/g, "$1")
```

gives the same error as #84

**Comment by eventualbuddha** [comment]
[This](http://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=true&code=%2F%5C%2F%5C%2F%2F) is probably the smallest reproducible test case I can find for this: `/\/\//`

**Comment by eventualbuddha** [comment]
Fixed in v1.41.4.
