### ISSUE TITLE
Indenting error, and generated code syntax error

### ISSUE THREAD

**Issue by jcalfee** [eventualbuddha/decaffeinate#109]
The first is a minor error where it looks like `+` is not recognized as a line continuation:
```bash
curl https://raw.githubusercontent.com/cryptonomex/graphene-ui/master/dl/src/chain/serializer_validation.coffee | decaffeinate | egrep "{)" 
...
125 :                 "#{reserved_spaces}.#{object_type}.[0-9]+ "+
^^^ :                ^
```
If you fix that or work-around (save the file and remove that \n) then `decaffenate` will generate invalid JavaScript:

`        if (is_empty(value) {)`

It looks like the { and ) are transposed...

**Comment by eventualbuddha** [comment]
The transposition was fixed in v1.44.1. I opened #110 to track the trailing binary operator bug.
