### ISSUE TITLE
Could not fix range for AssignOp at line X

### ISSUE THREAD

**Issue by patelsan** [eventualbuddha/decaffeinate#115]
It's running into this error, here X > total line count. Any ideas or thoughts would be greatly appreciated.

**Comment by eventualbuddha** [comment]
Most likely it's rewriting it internally and causing the line numbers not
to match. Can you share the code that breaks it?

**Comment by eventualbuddha** [comment]
Ping @patelsan.

**Comment by patelsan** [comment]
@eventualbuddha Sorry for the late reply, I was able to zero down on the line causing it - seems to be related to RegEx, here is a snippet to reporduce this

```coffeescript
class ControllerBase
  @register:(name = null)->
    name ?= @name || @toString().match(/function\s*(.*?)\(/)?[1]
```

**Comment by eventualbuddha** [comment]
@patelsan Odd, that example [seems not to crash](http://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=false&code=class%20ControllerBase%0A%20%20%40register%3A(name%20%3D%20null)-%3E%0A%20%20%20%20name%20%3F%3D%20%40name%20%7C%7C%20%40toString().match(%2Ffunction%5Cs*(.*%3F)%5C(%2F)%3F%5B1%5D%0A) with the latest version, although it leaves `name ?= …` which is clearly wrong (#38). Perhaps that's not the part that causes it?

**Comment by eventualbuddha** [comment]
@patelsan #38 is now fixed, but your code also showed causes another bug. I opened #118 to track it.

**Comment by eventualbuddha** [comment]
And now #118 is fixed. Added #119 to track the remaining issue from this one.
