### ISSUE TITLE
Comparison operators don't work?

### ISSUE THREAD

**Issue by namuol** [eventualbuddha/decaffeinate#14]
All the basic comparison operators appear to be unsupported.

For instance, if I run this:
```shell
echo "a == b" | decaffeinate
```

`traverse.js` complains like so:

```
Error: cannot traverse unknown node type: EQOp
```

I get the same results for any other comparison operators, as well.

Here's a list of all I tried and their associated AST node names (I may be missing some operators):

* `EQOp` (`==`, `is`)
* `NEQOp` (`!=`, `isnt`)
* `GTOp` (`>`)
* `GTEOp` (`>=`)
* `LTOp` (`<`)
* `LTEOp` (`<=`)
* `UrnaryExistsOp` (`<expr>?`)
* `BitAndOp` (`&`)
* `BitOrOp` (`|`)
* `BitXorOp` (`^`)

**Comment by eventualbuddha** [comment]
Thanks for highlighting this. All of these should be fixed in v1.6.0.
