### ISSUE TITLE
formatParserError 

### ISSUE THREAD

**Issue by davidpp** [eventualbuddha/decaffeinate#20]
Hi!

I was expecting to have some manual work to do to completely convert, but so far, I'm getting error on the first character of most of my file.  Here is an example :

If I can help debug that problem, do not hesitate :)

````
~$ decaffeinate coffee.coffee

/usr/local/lib/node_modules/decaffeinate/node_modules/coffee-script-redux/lib/module.js:61
      throw new Error(formatParserError(preprocessed, e));
            ^
Error: Syntax error on line 1, column 1: unexpected '"' (\u0022)
1 : angular.module("driverLogs")
^ : ^

**Comment by eventualbuddha** [comment]
CoffeeScriptRedux (the parser used by this project) has some problems with parsing. Specifically, it doesn't parse all CoffeeScript code that the official parser would, and it sometimes reports errors as occurring at the wrong character.

It would be great if you could come up with a minimal failing example by essentially removing halves of your file content (while still remaining vaild CS) until you figure out what caused the parse error, then remove everything else not required to cause the issue.

Alternatively you can just paste the whole file here and I'll figure it out.

**Comment by davidpp** [comment]
Ah ok, I understand now, make sense.  I'll do that until I find exactly which part is causing it and will report it here.

Thanks for your time.

**Comment by eventualbuddha** [comment]
@davidpp any luck? If you don't have time, I stand by my offer to take the raw file and find the issue myself.

**Comment by davidpp** [comment]
Hi!

Found an easy way to reproduce, issue seem to be with method chaining with indentation like this :

```coffeescript
angular.module("testModule")
  .controller "testCtrl", (test) ->
    console.log(test)
```

If I change it to this, it work :

```coffeescript
angular.module("test").controller "testCtrl", (test) ->
  console.log(test)
```

**Comment by eventualbuddha** [comment]
It is a limitation of CoffeeScriptRedux. I'm going to close this since it's not tracking something I need to do. Thanks for pointing it out, though.
