### ISSUE TITLE
Misleading subtitle

### ISSUE THREAD

**Issue by DavidBruant** [eventualbuddha/decaffeinate#24]
Context:
https://twitter.com/g_marty/status/580433557941805057

Maybe change it to "Convert your CoffeeScript to ES6" ?

**Comment by eventualbuddha** [comment]
I changed it to "CoffeeScript in, ES6 out". Is that clearer?

**Comment by DavidBruant** [comment]
<3

**Comment by eventualbuddha** [comment]
@DavidBruant I also changed the README to include that short snippet and a sentence about why the project exists. Thanks for the interest! What are you thinking of using it for?
