### ISSUE TITLE
Support for "++"/"--" (pre and post) and "+="

### ISSUE THREAD

**Issue by Dignifiedquire** [eventualbuddha/decaffeinate#36]
All these operators throw with `Error: cannot traverse unknown node type:` at the moment, would be great if they could be added

**Comment by eventualbuddha** [comment]
I'll take a look at this soon. Thanks for pointing it out!

**Comment by Dignifiedquire** [comment]
Thank you for a great tool

**Comment by eventualbuddha** [comment]
Mostly fixed in v1.19.2. Increment and decrement now work, but compound assignment only works in the same cases it works in JavaScript. Don't expect `||=`, `&&=`, or `?=` to work yet.
