### ISSUE TITLE
Error: Cannot overwrite the same content twice, when defining property

### ISSUE THREAD

**Issue by darkoverlordofdata** [eventualbuddha/decaffeinate#46]
this works:

```coffee
class Scooby
  constructor: (doo) ->
    @doo = doo
```

this throws an error:

```coffee
class Scooby
  snack: 42
  constructor: (doo) ->
    @doo = doo
```

**Comment by eventualbuddha** [comment]
I've verified that this happens for me too. I haven't figured out what causes it yet, but it appears to be trying to replace `->` twice.

**Comment by eventualbuddha** [comment]
I'm happy to report this [works as expected in the latest version](https://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=false&experimental=false&playground=false&loose=false&spec=false&code=class%20Scooby%0A%20%20snack%3A%2042%0A%20%20constructor%3A%20(doo)%20-%3E%0A%20%20%20%20%40doo%20%3D%20doo)!

```js
class Scooby {
  snack = 42;
  constructor(doo) {
    this.doo = doo;
  }
}
```
