### ISSUE TITLE
Cmd-L key binding is overloaded on Chrome and Firefox for Mac

### ISSUE THREAD

**Issue by JasonBenn** [eventualbuddha/decaffeinate#57]
On Firefox and Chrome for Mac (and probably other browsers), Cmd-L selects the search and URL field of the browser.  Decaffeinate overrides this with the "go to line number" functionality.  Not a huge priority, obviously, but it was a surprise.

It may be worthwhile to remove this binding or change the shortcut (or perhaps allow the user to create their own key bindings, or choose a set of key bindings).  If we do decide to change, then Ctl-G is a good candidate - it's the default key binding for "go to line number" in Sublime Text.

**Comment by eventualbuddha** [comment]
This behavior is probably standard for the editor library I'm using. I've been annoyed by it too. I'll see if I can change it to Ctrl+G.

**Comment by eventualbuddha** [comment]
Fixed by 3b67d6fe39b8f3e27a7d053ed5e553b0be7d56b0. Just removed for now instead of using Ctrl+G.
