### ISSUE TITLE
little arrow inside an object literal does not convert properly

### ISSUE THREAD

**Issue by christopherthielen** [eventualbuddha/decaffeinate#60]
Given this test case: 
```
works =
  foo: (service) => service.fetch()

fails =
  foo: (service) -> service.fetch()
```
I get the following output: 

```
var works =
  {foo: (service) => service.fetch()};

var fails =
  {foo(service) { return service.fetch(); }};
```

**Comment by eventualbuddha** [comment]
Thanks for the report! I'm having trouble understanding what output you're expecting. Could you clarify? The only obvious things I see are that the braces should be written like so:

```
var fails = {
  foo(service) { return service.fetch(); }
};
```

And that perhaps you're not expecting the shorthand function syntax and want this instead?

```
var fails = {
  foo: function(service) { return service.fetch(); }
};
```

If the latter, note that the shorthand is valid ES6 syntax.

**Comment by christopherthielen** [comment]
Oh, I didn't know the es6 function shorthand syntax was valid outside of a class.  I was indeed expecting the latter and thought the former was invalid.
