### ISSUE TITLE
Chained function invocation on next line does not allow extra indent

### ISSUE THREAD

**Issue by christopherthielen** [eventualbuddha/decaffeinate#62]
I'm not sure if this is legit way to chain a method call, but it's all over my code base.
```
$stateProvider
  .state 'foo'
  .state 'bar'
```
leads to:
```
Error: Syntax error on line 2, column 9: unexpected '\'' (\u0027)
1 : $stateProvider
2 :   .state 'foo'
^ :        ^
3 :   .state 'bar'
4 :
```

 ----

The function call is chained if the indent level is the same
```
$stateProvider
.state 'foo'
```
leads to:
```
$stateProvider
.state( 'foo'
);
```
which is OK. However, chaining an additional function call is broken (see #63)

**Comment by christopherthielen** [comment]
dupe #51

**Comment by eventualbuddha** [comment]
This is valid CoffeeScript syntax. I've started working to switch away from CoffeeScriptRedux, which doesn't parse things like this properly, to the official CoffeeScript parser (which obviously does!). See https://github.com/eventualbuddha/decaffeinate-parser/commit/c11abb8ec3e6eb3b2a7f0de9221b7677c92c26a0.

**Comment by christopherthielen** [comment]
I'm sure switching to the official CS parser will address a lot of issues.  I thought you chose Redux because CS didn't expose the AST nicely like Redux?  Do you have an idea how much work it will be to swap it out?

**Comment by eventualbuddha** [comment]
You're right, I did choose Redux because it has a better AST. The eventualbuddha/decaffeinate-parser project aims to give me a similar AST but using the official CS parser. See #65 for more info.
