### ISSUE TITLE
Support transforming React.createElement to JSX

### ISSUE THREAD

**Issue by hannesj** [eventualbuddha/decaffeinate#66]
Now that #65 is going to land and we are getting working line continuations, I would have an additional feature request.

It is possible to use [cjsx-transform](https://github.com/jsdf/coffee-react-transform) to convert cjsx files to plain CoffeeScript before converting the file to JavaScript using decaffeinate. Unfortunately this leaves us with calls to React.createElement instead of the more elegant JSX syntax in the converted files. Would it be possible to (optionally) convert the calls to React.createElement into JSX syntax when writing JavaScript from the AST?

**Comment by eventualbuddha** [comment]
Thanks for the interest, @hannesj. What you're describing sounds to me like it's best done using a reverse transform on the JavaScript generated by decaffeinate. Such a thing could be done as a standalone tool, or as a Babel plugin, for example. If I see a way for decaffeinate to make this easier I'll keep it in mind, but likely decaffeinate is going to stay out of the business of handling JSX directly.
