### ISSUE TITLE
Comments at end of statement breaks parsing

### ISSUE THREAD

**Issue by blimmer** [eventualbuddha/decaffeinate#67]
For example, converting this:
```coffee
foo = ->
  bar.then ->
    return 'bar' #should return bar
```

```js
var foo = function() {
  return bar.then(function() {
    return 'bar';);; //should return bar
  }
}
```

**Comment by eventualbuddha** [comment]
Thanks for the report! It's in the backlog.

Apologies for the delay on this. My daughter was born on Oct 12 so I'm only now getting back on top of things.

**Comment by blimmer** [comment]
No problem - thanks!

**Comment by eventualbuddha** [comment]
[Fixed](http://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=true&code=foo%20%3D%20-%3E%0A%20%20bar.then%20-%3E%0A%20%20%20%20return%20'bar'%20%23should%20return%20bar%0A) in v1.42.0.
