### ISSUE TITLE
Support CJSX

### ISSUE THREAD

**Issue by DylanPiercey** [eventualbuddha/decaffeinate#78]
This may be out of scope, but would be handy!
https://github.com/jsdf/coffee-react

**Comment by eventualbuddha** [comment]
This wouldn't be too hard if there was an alternative CoffeeScript parser that treated these as part of the parse tree, but it looks like it is simply a pre-processor. That makes it pretty much a non-starter, unfortunately.

**Comment by flying-sheep** [comment]
too bad. i have a medium-sized codebase i’d like to convert which is full of JSX literals.

maybe we could hack something up using the CJSX preprocessor and a babel transform which does `React.createElement(...)` → `<...></...>`

**Comment by flying-sheep** [comment]
hi, so i created [babel-plugin-transform-react-createelement-to-jsx](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx#readme). that’s quite a mouthful, but actually would allow us to do like the README says:

> CJSX syntax → coffee-react-transform → decaffeinate → react-createelement-to-jsx → JSX syntax

**Comment by DylanPiercey** [comment]
@flying-sheep thats pretty sweet. +1 to that.

**Comment by flying-sheep** [comment]
damn, didn’t expect michaelficarra/CoffeeScriptRedux#325
