### ISSUE TITLE
on off keywords are not converted

### ISSUE THREAD

**Issue by netei** [eventualbuddha/decaffeinate#97]
http://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=true&code=f%3Don

Should be converted to true/false

**Comment by eventualbuddha** [comment]
This should be an easy one if anyone wants to take a crack at it. Just
create a `patchBoolean` function that checks the boolean nodes' `raw` value
for `on` or `off` and overwrites them with `true` and `false`.

cc @jeffchan @nickdima

**Comment by eventualbuddha** [comment]
I just added this and will push it shortly.
