### ISSUE TITLE
translations for let, const, import

### ISSUE THREAD

**Issue by bryce-larson** [eventualbuddha/decaffeinate#98]
It would be nice if there are additional support for some of the new es6 coding styles.  Not everyone might want these enabled, so they might need option flags to enable them. 

- translate `require` syntax to `import` syntax
- translate `var` to `let`
- translate `var` to `const` if only has single assignment, otherwise translate to `let`

Examples

```coffeescript
{myFoo} = require 'myFoo'
myBar = require 'myBar'

->
  bar = 'bar'
  foo = 'foo'
  foo = 'foobar'
  return
```

```javascript
import {myFoo} from 'myFoo';
import myBar from 'myBar';

(function() {
  const bar = 'bar';
  let foo = 'foo';
  foo = 'foobar';
  return;
});

**Comment by eventualbuddha** [comment]
It's definitely a worthwhile thing to have something that can transform ES5 to ES6. I could choose to embed that directly into decaffeinate, but I think a better approach is to use the rebooted [esnext](https://github.com/esnext/esnext) project to do that transformation. Here's what decaffeinate does to your code example:

```js
var {myFoo} = require('myFoo');
var myBar = require('myBar');

(function() {
  var bar = 'bar';
  var foo = 'foo';
  foo = 'foobar';
  return;
});
```

And here's what esnext v1.0.0 does to that:

```js
import { myFoo } from 'myFoo';
import myBar from 'myBar';

(function() {
  var bar = 'bar';
  var foo = 'foo';
  foo = 'foobar';
  return;
});
```

As you can see, `var` isn't transformed into `const` and `let` yet, but `require` is transfomed into `import`. Functions are also transformed to arrow functions in some cases:

```js
var a = function() { return 1; };
// vvv
var a = () => 1;
```

I would love to have your help with either project!
